### ISSUE TITLE
The prebuilt binary is missing dependencies

### ISSUE THREAD

**Issue by lolmanurfunny** [nurokoi/Roblox-FastLog-Console#1]
![image](https://github.com/nurokoi/Roblox-FastLog-Console/assets/77128366/05433965-5e44-4df1-942c-906bff7f0d1e)
![image](https://github.com/nurokoi/Roblox-FastLog-Console/assets/77128366/1024874f-e323-44fb-8718-730d4b821223)

**Comment by nurokoi** [comment]
Thank you for reporting this, the prebuilt binary should now work as intended. I have updated the [readme](https://github.com/nurokoi/Roblox-FastLog-Console/blob/main/README.md#compilation) to ensure this doesn't happen again.
